baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Al-Quran Digital Online Terjemahan dan Tafsir Bahasa Indonesia'

[params]
    description = 'Baca Al-Quran Digital Online dengan terjemahan dan tafsir dalam Bahasa Indonesia Lengkap 30 Juz' 

disableKinds = ['taxonomy', 'term'] 