baseURL = 'https://alcorao.netlify.app/'
languageCode = 'en-us'
title = 'Alcorão e Tafsir compilado por Ehgo'

[params]
    description = 'Alcorão e Tafsir em português'
    publishdate = '2006-01-02T15:04:05-07:00'

disableKinds = ['taxonomy', 'term'] 

enableRobotsTXT = true
