baseURL = 'https://alcorao.netlify.app/'
languageCode = 'en-us'
title = 'Alcorão e Tafsir compilado por Ehgo'

[params]
    description = 'Baca Al-Quran Digital Online dengan terjemahan dan tafsir dalam Bahasa Indonesia Lengkap 30 Juz' 
    publishdate = '2006-01-02T15:04:05-07:00'

disableKinds = ['taxonomy', 'term'] 

enableRobotsTXT = true
